# Generated by Django 5.1.5 on 2025-01-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_alter_customer_profile_pic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
