# Generated by Django 5.1.5 on 2025-02-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_alter_cart_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
