# Generated by Django 5.1.5 on 2025-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproduction',
            name='product',
        ),
        migrations.AddField(
            model_name='productproduction',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='product_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
