# Generated by Django 5.1.5 on 2025-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_remove_productproduction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
