# Generated by Django 5.1.5 on 2025-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_product_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
