# Generated by Django 5.1.4 on 2025-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_expiry_date_product_quantity_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
    ]
