# Generated by Django 5.1.4 on 2025-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_remove_product_expiry_date_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
